sudo: required
dist: trusty
language: node_js
node_js:
- node
before_script:
- npm install
script:
#- npm test
after_success:
- wt init --container "app63474144" --url "WEBTASK_TOKEN" -p "app63474144-eu"
- "npm run deploy"